### ISSUE TITLE
There's a repo for tutorial code

### ISSUE THREAD

**Issue by ice1000** [i-walker/arend-exercises#1]
https://github.com/arend-lang/tutorial-code

**Comment by i-walker** [comment]
Thanks :) I am aware of it. 
I am trying to add also other solutions and exercises in this repo.

**Comment by i-walker** [comment]
Regarding the tutorial code solutions: 
This repo is committed to accompanying the [tutorial-code](https://github.com/arend-lang/tutorial-code) with other use cases, scenarios and will remove the section [here](https://github.com/i-walker/arend-exercises/blob/master/src/arend/)

**Comment by i-walker** [comment]
Closing this as discussed in Telegram 👍
